#!/usr/bin/env python3
import requests
from datetime import datetime

url = "https://api-nba-v1.p.rapidapi.com/games/"

querystring_1 = {"league":"standard", "season":"2022","team":29}

headers = {
    'x-rapidapi-host': "api-nba-v1.p.rapidapi.com",
    'x-rapidapi-key': "25495a699amsh87ba522b0e7bd6dp1c4067jsnc4c8ebff8d81"
}

response = requests.request("GET", url, headers=headers, params=querystring_1)
response_data = response.json()

latest_game = ""
for game in response_data["response"]:
    if game["status"]["long"] == "Finished":
        latest_game = game

if latest_game["teams"]["home"]["id"] == 29:
    por_home = True
else:
    por_home = False

if por_home:
    por_points = int(latest_game["scores"]["home"]["points"])
    opp_points = int(latest_game["scores"]["visitors"]["points"])
else:
    por_points = int(latest_game["scores"]["visitors"]["points"])
    opp_points = int(latest_game["scores"]["home"]["points"])

print(f"{latest_game['teams']['visitors']['nickname']} at {latest_game['teams']['home']['nickname']}, {latest_game['date']['start']} UTC")

if por_points - opp_points >= -10:
    print("Watch this game")
else:
    print(f"Don't bother, they lost {por_points}-{opp_points}")
